import { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Faisal Adama Portfolio',
    short_name: 'FA Portfolio',
    description: 'Website portofolio pribadi Faisal Adama',
    start_url: '/',
    display: 'standalone',
    background_color: '#0A0A0A',
    theme_color: '#0A0A0A',
    icons: [
      {
        src: '/icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
      },
      {
        src: '/apple-icon.png', // This is dynamically generated by apple-icon.tsx
        sizes: '180x180',
        type: 'image/png',
      },
    ],
  };
}
